### PR TITLE
Use released Rubies for faster CI

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Review by AlexWayfer — APPROVED** [review]
See no problem with it.

**Comment by schneems** [comment]
The problem is circleci still hasn't released a `3.1` image so this fails. I'm guessing these ruby images are no longer maintained.

**Comment by AlexWayfer** [comment]
I can suggest only 2 (OK, 3) options:
1. Left as it was.
2. Switch to another CI, like Cirrus CI.
3. Find out a way to use images from Docker Hub.

**Comment by mishina2228** [comment]
Hi, it seems that we should use `cimg/ruby` instead of deprecated `circleci/ruby`.
`cimg/ruby:3.1` is already available.
Please see the following article for the details:
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

**Comment by schneems** [comment]
We updated some of the images in https://github.com/zombocom/dead_end/pull/141. Think we're good

**Pull request closed without merging**
